
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP1
 */
public class Startup extends javax.swing.JFrame {

    /**
     * Creates new form Startup
     */
    public Startup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JD_Artistas = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        TF_Nombre = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        TF_GeneroM = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        TF_N_Disco = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        TF_Alias = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        RB_instru = new javax.swing.JRadioButton();
        RB_voz = new javax.swing.JRadioButton();
        JB_AArtista = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JL_Artista = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        Tipo_de_musica = new javax.swing.ButtonGroup();
        JD_Albums = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        TF_GeneroM1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        RB_digital = new javax.swing.JRadioButton();
        TF_Alias1 = new javax.swing.JTextField();
        RB_CD = new javax.swing.JRadioButton();
        TF_Nombre1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        TF_Fecha_p = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        JL_Artista1 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        JL_Albums = new javax.swing.JList<>();
        JB_AgregarAlbumaA = new javax.swing.JButton();
        JB_AgregarAlbums = new javax.swing.JButton();
        Formato_p = new javax.swing.ButtonGroup();
        JB_simula = new javax.swing.JButton();
        JB_SalirSys = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        JB_Artistas = new javax.swing.JButton();
        JB_Albums = new javax.swing.JButton();
        JB_Canciones = new javax.swing.JButton();
        JB_PlayList = new javax.swing.JButton();

        JD_Artistas.setTitle("Artistas");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Artistas");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setText("Nombre de la disquera: ");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel16.setText("Nombre:");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel17.setText("Alias:");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel18.setText("Tipo de Musica: ");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setText("Genero de musica: ");

        Tipo_de_musica.add(RB_instru);
        RB_instru.setText("Instrumental");

        Tipo_de_musica.add(RB_voz);
        RB_voz.setText("De voz");

        JB_AArtista.setText("Agregar Artista");
        JB_AArtista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_AArtistaMouseClicked(evt);
            }
        });

        JL_Artista.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(JL_Artista);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Lista de Artistas en el sistema: ");

        javax.swing.GroupLayout JD_ArtistasLayout = new javax.swing.GroupLayout(JD_Artistas.getContentPane());
        JD_Artistas.getContentPane().setLayout(JD_ArtistasLayout);
        JD_ArtistasLayout.setHorizontalGroup(
            JD_ArtistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_ArtistasLayout.createSequentialGroup()
                .addGroup(JD_ArtistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JD_ArtistasLayout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addComponent(jLabel2))
                    .addGroup(JD_ArtistasLayout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(JB_AArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JD_ArtistasLayout.createSequentialGroup()
                .addGroup(JD_ArtistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JD_ArtistasLayout.createSequentialGroup()
                        .addGroup(JD_ArtistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel16))
                        .addGap(55, 55, 55)
                        .addGroup(JD_ArtistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TF_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TF_GeneroM, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(JD_ArtistasLayout.createSequentialGroup()
                        .addGroup(JD_ArtistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addGap(18, 18, 18)
                        .addGroup(JD_ArtistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TF_Alias, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TF_N_Disco, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(JD_ArtistasLayout.createSequentialGroup()
                                .addComponent(RB_instru)
                                .addGap(18, 18, 18)
                                .addComponent(RB_voz)))))
                .addGap(88, 88, 88)
                .addGroup(JD_ArtistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 29, Short.MAX_VALUE))
        );
        JD_ArtistasLayout.setVerticalGroup(
            JD_ArtistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_ArtistasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(11, 11, 11)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JD_ArtistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JD_ArtistasLayout.createSequentialGroup()
                        .addGroup(JD_ArtistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TF_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(JD_ArtistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(TF_GeneroM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(JD_ArtistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(TF_N_Disco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(JD_ArtistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(TF_Alias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(JD_ArtistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(RB_instru)
                            .addComponent(RB_voz))
                        .addGap(18, 18, 18)
                        .addComponent(JB_AArtista))
                    .addGroup(JD_ArtistasLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(158, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("Albums");

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel19.setText("Alias:");

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel20.setText("Formato de publicacion: ");

        Formato_p.add(RB_digital);
        RB_digital.setText("Digital");

        Formato_p.add(RB_CD);
        RB_CD.setSelected(true);
        RB_CD.setText("CD");

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel21.setText("Genero de musica: ");

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel22.setText("Fecha de producion: ");

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel23.setText("Nombre:");

        JL_Artista1.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(JL_Artista1);

        JL_Albums.setModel(new DefaultListModel());
        jScrollPane3.setViewportView(JL_Albums);

        JB_AgregarAlbumaA.setText("---->");
        JB_AgregarAlbumaA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_AgregarAlbumaAMouseClicked(evt);
            }
        });

        JB_AgregarAlbums.setText("Agregar Albums");
        JB_AgregarAlbums.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_AgregarAlbumsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout JD_AlbumsLayout = new javax.swing.GroupLayout(JD_Albums.getContentPane());
        JD_Albums.getContentPane().setLayout(JD_AlbumsLayout);
        JD_AlbumsLayout.setHorizontalGroup(
            JD_AlbumsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_AlbumsLayout.createSequentialGroup()
                .addGroup(JD_AlbumsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JD_AlbumsLayout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(JD_AlbumsLayout.createSequentialGroup()
                        .addGroup(JD_AlbumsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JD_AlbumsLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(JD_AlbumsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel19))
                                .addGap(41, 41, 41)
                                .addGroup(JD_AlbumsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TF_Alias1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TF_Nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(JD_AlbumsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(TF_GeneroM1)
                                        .addComponent(TF_Fecha_p, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(JD_AlbumsLayout.createSequentialGroup()
                                        .addComponent(RB_digital)
                                        .addGap(18, 18, 18)
                                        .addComponent(RB_CD)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 457, Short.MAX_VALUE)
                                        .addComponent(JB_AgregarAlbumaA)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(JD_AlbumsLayout.createSequentialGroup()
                                .addGap(171, 171, 171)
                                .addComponent(JB_AgregarAlbums, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(JD_AlbumsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JD_AlbumsLayout.createSequentialGroup()
                    .addContainerGap(500, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(388, 388, 388)))
        );
        JD_AlbumsLayout.setVerticalGroup(
            JD_AlbumsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_AlbumsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGroup(JD_AlbumsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JD_AlbumsLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(JD_AlbumsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TF_Nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23))
                        .addGap(14, 14, 14)
                        .addGroup(JD_AlbumsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(TF_Fecha_p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(JD_AlbumsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(TF_GeneroM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(JD_AlbumsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JD_AlbumsLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(JD_AlbumsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel20)
                                    .addComponent(RB_digital)
                                    .addComponent(RB_CD)))
                            .addGroup(JD_AlbumsLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(JB_AgregarAlbumaA)))
                        .addGap(18, 18, 18)
                        .addGroup(JD_AlbumsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TF_Alias1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addGap(18, 18, 18)
                        .addComponent(JB_AgregarAlbums))
                    .addGroup(JD_AlbumsLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(241, Short.MAX_VALUE))
            .addGroup(JD_AlbumsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JD_AlbumsLayout.createSequentialGroup()
                    .addGap(58, 58, 58)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(240, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Start up");

        JB_simula.setText("Simulacion");

        JB_SalirSys.setText("Salir de sistema");
        JB_SalirSys.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_SalirSysMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Bienvenidos al sistema: ");

        jToolBar1.setRollover(true);

        JB_Artistas.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        JB_Artistas.setText("Artistas");
        JB_Artistas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_ArtistasMouseClicked(evt);
            }
        });
        jToolBar1.add(JB_Artistas);

        JB_Albums.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        JB_Albums.setText("Albums");
        JB_Albums.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_AlbumsMouseClicked(evt);
            }
        });
        jToolBar1.add(JB_Albums);

        JB_Canciones.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        JB_Canciones.setText("Canciones");
        jToolBar1.add(JB_Canciones);

        JB_PlayList.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        JB_PlayList.setText("Playlist");
        jToolBar1.add(JB_PlayList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(JB_simula)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JB_SalirSys)
                        .addGap(58, 58, 58)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(58, 58, 58)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB_simula)
                    .addComponent(JB_SalirSys))
                .addContainerGap(105, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JB_AArtistaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_AArtistaMouseClicked
        // TODO add your handling code here:
        String t="";
        if(RB_instru.isSelected()){
            t="Instrumental";
        }else{
            t="Su voz";
        }
         Artista a = new Artista(TF_Nombre.getText(),TF_GeneroM.getText(),TF_N_Disco.getText(),TF_Alias.getText(),t
                );
    
        Administrar_Artistas ap = new Administrar_Artistas("./Astista.cana");
        ap.cargarArchivo();
        ap.setArtistas(a);
        ap.escribirArchivo();
        JOptionPane.showMessageDialog(this,
                "Artista guardado exsitosamente");
         DefaultListModel modelo = (DefaultListModel) JL_Artista.getModel();
        modelo.addElement(a);
        JL_Artista.setModel(modelo);
        JL_Artista1.setModel(modelo);
        TF_Nombre.setText("");
        TF_GeneroM.setText("");
        TF_GeneroM.setText("");
        TF_N_Disco.setText("");
        TF_Alias.setText("");
        RB_instru.setSelected(false);
        RB_voz.setSelected(true);
    }//GEN-LAST:event_JB_AArtistaMouseClicked

    private void JB_SalirSysMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_SalirSysMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_JB_SalirSysMouseClicked

    private void JB_ArtistasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_ArtistasMouseClicked
        // TODO add your handling code here:
        JDArtista();
    }//GEN-LAST:event_JB_ArtistasMouseClicked

    private void JB_AgregarAlbumsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_AgregarAlbumsMouseClicked
        // TODO add your handling code here:
        String t="";
        if(RB_digital.isSelected()){
            t="Digital";
        }else{
            t="CD";
        }
         Albums a = new Albums(TF_Nombre1.getText(),TF_Fecha_p.getText(),TF_GeneroM1.getText(),t,TF_Alias1.getText()
                );

        JOptionPane.showMessageDialog(this,
                "Album guardado exsitosamente");
         DefaultListModel modelo = (DefaultListModel) JL_Albums.getModel();
        modelo.addElement(a);
        JL_Albums.setModel(modelo);
        TF_Nombre1.setText("");
        TF_GeneroM1.setText("");
        TF_Fecha_p.setText("");
        TF_Alias1.setText("");
        RB_digital.setSelected(false);
        RB_CD.setSelected(true);
    }//GEN-LAST:event_JB_AgregarAlbumsMouseClicked

    private void JB_AgregarAlbumaAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_AgregarAlbumaAMouseClicked
        // TODO add your handling code here:
       
        DefaultListModel modelo = (DefaultListModel) JL_Albums.getModel();
        int t1=JL_Artista1.getSelectedIndex();
        int t2=JL_Albums.getSelectedIndex();
        Administrar_Artistas ap = new Administrar_Artistas("./Astista.cana");
        ap.cargarArchivo();
            Albums a=(Albums)modelo.get(t2);
                    /*
                    ar.getListaArtistas().get(p).setAlias(JOptionPane.showInputDialog("Alias del Artista: "));
                    ((Artistas) modeloLISTA.get(JL_ListarArtista.getSelectedIndex())).setNombre(ar.getListaArtistas().get(p).getNombre());
                    */
            ap.getListaArtistas().get(t1).getA().add(a);
            ap.escribirArchivo();
            DefaultListModel modelo1 = (DefaultListModel) JL_Artista1.getModel();
           ((Artista) modelo1.get(t1)).getA().add(a);
           JL_Artista1.setModel(modelo1);
           JL_Artista.setModel(modelo1);
           System.out.println(ap.getListaArtistas().get(t1).getA());
    }//GEN-LAST:event_JB_AgregarAlbumaAMouseClicked

    private void JB_AlbumsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_AlbumsMouseClicked
        // TODO add your handling code here:
        JDALBUMS();
    }//GEN-LAST:event_JB_AlbumsMouseClicked

    /**
     * @param args the command line arguments
     */
     public void JDArtista(){
        JD_Artistas.pack();
        JD_Artistas.setModal(true);
        JD_Artistas.setLocationRelativeTo(this);
        JD_Artistas.setVisible(true);
    }
     public void JDALBUMS(){
        JD_Albums.pack();
        JD_Albums.setModal(true);
        JD_Albums.setLocationRelativeTo(this);
        JD_Albums.setVisible(true);
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Startup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Startup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Startup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Startup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Startup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Formato_p;
    private javax.swing.JButton JB_AArtista;
    private javax.swing.JButton JB_AgregarAlbumaA;
    private javax.swing.JButton JB_AgregarAlbums;
    private javax.swing.JButton JB_Albums;
    private javax.swing.JButton JB_Artistas;
    private javax.swing.JButton JB_Canciones;
    private javax.swing.JButton JB_PlayList;
    private javax.swing.JButton JB_SalirSys;
    private javax.swing.JButton JB_simula;
    private javax.swing.JDialog JD_Albums;
    private javax.swing.JDialog JD_Artistas;
    private javax.swing.JList<String> JL_Albums;
    private javax.swing.JList<String> JL_Artista;
    private javax.swing.JList<String> JL_Artista1;
    private javax.swing.JRadioButton RB_CD;
    private javax.swing.JRadioButton RB_digital;
    private javax.swing.JRadioButton RB_instru;
    private javax.swing.JRadioButton RB_voz;
    private javax.swing.JTextField TF_Alias;
    private javax.swing.JTextField TF_Alias1;
    private javax.swing.JTextField TF_Fecha_p;
    private javax.swing.JTextField TF_GeneroM;
    private javax.swing.JTextField TF_GeneroM1;
    private javax.swing.JTextField TF_N_Disco;
    private javax.swing.JTextField TF_Nombre;
    private javax.swing.JTextField TF_Nombre1;
    private javax.swing.ButtonGroup Tipo_de_musica;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
